### ISSUE TITLE
elevenlabs.api.error.APIError: A voice for the voice_id ENfvYmv6CRqDodDZTieQ was not found.

### ISSUE THREAD

**Issue by dep** [cbh123/sloucher#1]
I get this error upon loading. Interestingly, I don't see a reference to ElevenLabs or OpenAI API keys anyplace. Where do I provide these?  How might I go about fixing this:

```
Traceback (most recent call last):
  File "/Users/dpeck/Sites/sloucher/narrator.py", line 101, in <module>
    main()
  File "/Users/dpeck/Sites/sloucher/narrator.py", line 92, in main
    play_audio(analysis)
  File "/Users/dpeck/Sites/sloucher/narrator.py", line 27, in play_audio
    audio = generate(text=text, voice="ENfvYmv6CRqDodDZTieQ", model="eleven_turbo_v2")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dpeck/Sites/sloucher/venv/lib/python3.11/site-packages/elevenlabs/simple.py", line 73, in generate
    return TTS.generate(text, voice, model, api_key=api_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dpeck/Sites/sloucher/venv/lib/python3.11/site-packages/elevenlabs/api/tts.py", line 45, in generate
    response = API.post(url, json=data, api_key=api_key)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dpeck/Sites/sloucher/venv/lib/python3.11/site-packages/elevenlabs/api/base.py", line 75, in post
    return API.request(url, method="post", *args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dpeck/Sites/sloucher/venv/lib/python3.11/site-packages/elevenlabs/api/base.py", line 67, in request
    raise APIError(message, status)
elevenlabs.api.error.APIError: A voice for the voice_id ENfvYmv6CRqDodDZTieQ was not found.
```

**Comment by dep** [comment]
I did sort out the API key bit:

```
from elevenlabs import set_api_key

set_api_key("<key>")
```

I'm guessing the Attenborough voice ID is within your personal account and not part of the public voice gallery that ElevenLabs provides. That's too bad!

**Comment by dep** [comment]
Also FWIW I also had to manually create the `./frames` folder for the capture script to save. You might create the folder with a single file in there so git keeps the folder in src.

**Comment by dep** [comment]
I also had to manually install a few other deps:

- cv2
- simpleaudio
-  Pillow
